<?php
/**
 * @file
 * Code for the devengine_core feature.
 */

include_once 'devengine_core.features.inc';

/**
 * Implements hook_menu().
 */
function devengine_core_menu() {
  $items = array();

  $items['admin/config/devengine'] = array(
    'title' => 'Devengine',
    'description' => 'Dev Engine',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/devengine/settings'] = array(
    'title' => 'Devengine settings',
    'description' => 'Dev Engine settings',
    'file' => 'devengine_core.admin.inc',
    'access arguments' => array('access administration pages'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('devengine_core_main_settings'),
  );

  return $items;
}

/**
 * Implements hook_preprocess_page().
 */
function devengine_preprocess_page(&$variables) {
  if (variable_get('devengine_core_logged_access', TRUE) && user_is_anonymous() && arg(0) != 'user') {
    drupal_goto('user');
  }
}

/**
 * Implements hook_block_info().
 */
function devengine_core_block_info() {
  $blocks['devengine_core_project_menu'] = array(
    'info' => t('Devengine core: Project menu'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function devengine_core_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'devengine_core_project_menu':
      $block['subject'] = t('Project menu');
      $block['content'] = devengine_core_project_menu_markup();
      break;

  }

  return $block;
}

/**
 * Markup for devengine_core_project_menu.
 */
function devengine_core_project_menu_markup() {
  // @TODO need a way to add links via UI.
  $nid = arg(1);
  $build_menu = FALSE;
  if (!empty($nid) && is_numeric($nid)) {
    $node_arg = node_load($nid);
    if ($node_arg->type == 'project') {
      $build_menu = TRUE;
      $node = $node_arg;
    }

    if ($node_arg->type == 'book') {
      if (!empty($node_arg->book['bid'])) {
        $wiki_config = devengine_wiki_load_book_config($node_arg->book['bid']);
        if (!empty($wiki_config['project_id'])) {
          $node = node_load($wiki_config['project_id']);
          $build_menu = TRUE;
        }
      }
    }
  }

  if ($build_menu && $node) {
    $items = array();
    $items[] = l(t('Issues'), 'projects/' . $node->nid . '/issues');
    $items[] = l(t('New issue'), 'projects/' . $node->nid . '/new-issue');
    $items[] = l(t('Latest Activity'), 'projects/' . $node->nid . '/activity');
    $items[] = l(t('Wiki'), 'projects/' . $node->nid . '/wiki');
    $items[] = l(t('Repository'), 'projects/' . $node->nid . '/repository');
    return theme('item_list', array('items' => $items));
  }
  return FALSE;
}
