#!/bin/bash

: '
Example of using:

sudo chmod a+x setup_repository
./setup_repository /opt/git/instance1 /home/vagrant/sites/instance1development /home/vagrant/sites/instance1staging /home/vagrant/sites/instance1production

/opt/git/instance1 - repository without a working directory
/home/vagrant/sites/instance1development - development repository
/home/vagrant/sites/instance1staging - staging repository
/home/vagrant/sites/instance1production - production repository
'

function create_bare_repository {
  mkdir -p $1
  cd $1
  git --bare init
}

function create_repository {
  mkdir $1
  cd $1
  git init
  git config core.fileMode false
  git remote add origin $2
  git pull origin master
}

function create_repository_initial {
  mkdir $1
  cd $1
  git init
  git config core.fileMode false
  touch test
  git add .
  git commit -m "Initial commit."
  git remote add origin $2
  git push origin master
}

function create_hook {
  touch $1/hooks/post-receive
  echo "#!/bin/sh
cd $2
env -i git pull origin master
echo Auto-checkout on development successful." > $1/hooks/post-receive
  chmod a+x $1/hooks/post-receive
}

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
    echo "You should enter 3 arguments."
    echo "Example: ./setup_repository /opt/git/instance1 /sites/development /sites/staging /sites/production"
    exit
fi

OPTIONS="Yes No"

# Create bare repository.
if [ -d "$1" ]; then
  echo "Directory $1 already exist"
  exit
else
  echo "Create repository without a working directory at $1?"
  select opt in $OPTIONS; do
    if [ "$opt" = "Yes" ]; then
      create_bare_repository $1
      create_hook $1 $2
      break
    elif [ "$opt" = "No" ]; then
      exit
    else
      echo "Bad option"
    fi
  done
fi

# Create development repository.
if [ -d "$2" ]; then
  echo "Directory $2 already exist"
  exit
else
  echo "Create empty repository for development at $2?"
  select opt in $OPTIONS; do
    if [ "$opt" = "Yes" ]; then
      create_repository_initial $2 $1
      break
    elif [ "$opt" = "No" ]; then
      exit
    else
      echo "Bad option"
    fi
  done
fi

# Create staging repository.
if [ -d "$3" ]; then
  echo "Directory $3 already exist"
  exit
else
  echo "Create empty repository for staging at $3?"
  select opt in $OPTIONS; do
    if [ "$opt" = "Yes" ]; then
      create_repository $3 $1
      break
    elif [ "$opt" = "No" ]; then
      exit
    else
      echo "Bad option"
    fi
  done
fi

# Create production repository.
if [ -d "$4" ]; then
  echo "Directory $4 already exist"
  exit
else
  echo "Create empty repository for production at $4?"
  select opt in $OPTIONS; do
    if [ "$opt" = "Yes" ]; then
      create_repository $4 $1
      break
    elif [ "$opt" = "No" ]; then
      exit
    else
      echo "Bad option"
    fi
  done
fi

echo "Successful!"
exit
